# Generated by Django 6.0.3 on 2026-03-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='images',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
